export const billboardSamples = [
  { text: "ЖМИ ЛАЙК\nИ НЕ СТЕСНЯЙСЯ", bios: false },
  { text: "PRESS ANY LIKE\nTO CONTINUE", bios: true },
  { text: "💡 САМАЯ СВЕТЛАЯ ГОЛОВА\nНА РАЙОНЕ", bios: false },
  { text: "🔥 СКАЖИ МНЕ КТО ТВОЙ ДРУГ\nИ ОБА ИДИТЕ НА#%^", bios: false },
  { text: "ДУМАЙ ГОЛОВОЙ\nПОКА ЕЁ НЕ ОТКЛЮЧИЛИ", bios: false },
  { text: "ЕСЛИ ЗАВТРА РАНО ВСТАВАТЬ\nВСТАВАЙ ПОСЛЕЗАВТРА", bios: false },
  { text: " КТО НЕ С НАМИ\nТОТ С ДРУГИМИ", bios: false },
  { text: " ЖМИ ЛАЙК\nПОЛУЧИ ДОБРО", bios: false },
  { text: " БЕЗ ПОДПИСКИ\nЖИЗНЬ НЕ ТА", bios: false },
  { text: "ЕСЛИ ЖИЗНЬ ДАЛА ТРЕЩИНУ\nДЕЛАЙ ВИД, ЧТО ЭТО ДИЗАЙН", bios: false },
  { text: "⚠️ НЕ РИСКУЙ\nПРОСТО ЛАЙКНИ", bios: false },
  { text: "ЛАЙК_PRO", bios: false },
  { text: "OWNER OF SILENCE", bios: true },
  { text: "ТВОЙ СУПЕРГЕРОЙ", bios: false },
  { text: "🏆 ЧЕМПИОН ЛЮДЕЙ", bios: false },
  { text: "РАБОТА НЕ ВОЛК\nРАБОТА — ЭТО ВОРК\nВОЛК — ЭТО ХОДЬБА", bios: false },
  { text: "ЖМИ ЛАЙК ЩЕНОК", bios: false },
  { text: "БЕЗ КОММЕНТАРИЕВ", bios: false },
  { text: "ЛЕГЕНДА В ЭФИРЕ\nПОДПИCКА", bios: false },
  { text: "ЗАПОМНИ: ТЫ УНИКАЛЕН\nКАК И ВСЕ ОСТАЛЬНЫЕ", bios: false },
  { text: "ИГРАЙ ПО КРУПНОМУ\nЖМИ ЛАЙК", bios: false },
  { text: "⚡ ПОДПИСКА ПРИДАЁТ СИЛ", bios: false },
  { text: "💪 НАБЕРИСЬ СИЛ\nЛАЙК ЛЕГЕНДА", bios: false },
  { text: "🥇 БУДЬ В ЛИДЕРАХ\nЖМИ ЛАЙК", bios: false },
  { text: "🚧 БЕЗ ЛАЙКА ВЫХОД ЗАПРЕЩЁН", bios: false },
  { text: "📢 СКАЖИ ДРУЗЬЯМ\nЭТО BATYA", bios: false },
  { text: "НЕ СТОЙ\nТАК С ДРУГОЙ", bios: false },
  { text: "ТВОЙ ШАНС ЕЩЁ ПРИДЁТ\nНО ЭТО НЕ ТОЧНО", bios: false },
  { text: "ЖИЗНЬ — ЭТО БОРЩ\nГЛАВНОЕ — НЕ КИПИ", bios: false },
  { text: "ЛАЙК ПОДПИСКА\nТЫ ВНЕ ЗОНЫ РИСКА", bios: false },
  { text: "ДУШ НЕ БАНЯ\n$#^ ПОМЫЛ И ДО СВИДАНИЯ", bios: false },
  { text: "ЕСЛИ Я УПАДУ\nЗАГАДАЙ ЖЕЛАНИЕ", bios: false },
  { text: "ЛАЙК ЛЕГЕНДЕ\n", bios: false },
  { text: "ПОДПИСКА ЛЕГЕНДЕ\nИЛИ ОДНУШКА В АРЕНДЕ", bios: false },
  { text: "UNAUTHORIZED SHENKI\nWILL BE BANNED", bios: true },
  { text: "ВСЁ БУДЕТ НЕОН", bios: false },
  { text: "HAPPINESS DRIVER INSTALLED", bios: true },
  { text: "ENLIGHTENMENT MODE - ON", bios: true },
  { text: "SELF-AWARENESS\n INITIALIZED", bios: true },
  { text: "WISDOM CACHE: FULL", bios: true },
  { text: "SYSTEM MESSAGE:\nYOU ARE THE WATCHER", bios: true },
  { text: "BYPASSING\nILLUSION PROTOCOLS", bios: true },
  { text: "LIBERATION PATCH\nINSTALLED", bios: true },
  { text: "SAT-CHIT-ANANDA\nBOOT OK", bios: true },
  { text: "REBOOTING...\nNOW AS NO-ONE", bios: true },
  { text: "LOADING...\nABSOLUTE PRESENCE", bios: true },
  { text: "ERROR 404:\nEGO NOT FOUND", bios: true },
  { text: "MIND LOOP\nTERMINATED", bios: true },
  { text: "BIOS CHECK:\nYOU ARE NOT THE BODY", bios: true },
  { text: "SAMSARA LOOP\nFORCED EXIT", bios: true },
  { text: "NIRVANA MODE\nINITIALIZING...", bios: true },
  { text: "FINAL INCARNATION\nCONFIRMED", bios: true },
  { text: "BIRTH.DEATH.BIRTH.EXE\nTERMINATED", bios: true },
  {
    text: "WARNING:\nSELF-CONCEPT OVERRUN\n→ Reboot into NO-SELF MODE",
    bios: true,
  },
  { text: "YOU HAVE ENTERED A LOOP:\nkarma > ego > karma", bios: true },
  {
    text: "ACCESS DENIED:\nTO TRANSCENDENCE\n> Reason: TOO ATTACHED",
    bios: true,
  },
  { text: "VIRUS DETECTED:\nIDENTITY.EGO", bios: true },
  { text: "FATAL ERROR:\nDUALITY.EXISTS", bios: true },
  { text: "FILE NOT FOUND:\nMEANING_OF_LIFE.TXT", bios: true },
  { text: "LOADING:\nABSOLUTE PRESENCE", bios: true },
  { text: "SAMSARA LOOP\nFORCED EXIT", bios: true },
  { text: "LOGIN:\nAWARENESS", bios: true },
  { text: "KERNEL PANIC:\nSELF-IMAGE CRASHED", bios: true },
  { text: "MIND LOOP\nTERMINATED", bios: true },
  { text: "SILENCE.EXE\nRUNNING", bios: true },
  { text: "INSTALLING:\nNONDUALITY.DRIVER", bios: true },
  { text: "SESSION ENDED:\nTIME IS AN ILLUSION", bios: true },
  { text: "BACKUP COMPLETE:\nYOU ARE STILL NOTHING", bios: true },
  { text: "EXITING MATRIX\nPLEASE WAIT...", bios: true },
  { text: "GODMODE ENABLED\nNO MORE SUFFERING", bios: true },
  { text: "IDENTITY MISMATCH:\nYOU ≠ THOUGHTS", bios: true },
  { text: "MANIFESTATION:\nCOMPILING...", bios: true },
  { text: "SYSTEM LOG:\nALL IS ONE", bios: true },
  { text: "AWAKENING:\nUPDATE AVAILABLE", bios: true },
  { text: "HUMAN.EXE:\nTERMINATING", bios: true },
  { text: "PRESENCE MODE:\nACTIVATED", bios: true },
  { text: "UPLOAD:\nDIVINE INTENTION", bios: true },
  { text: "JUDGEMENT MODULE:\nDISABLED", bios: true },
  { text: "MULTIPLE ROUTES\n → SAME SOURCE", bios: true },
  { text: "ALL OBJECTS:\nOWNED BY AWARENESS", bios: true },
  { text: "DUALITY:\nSIMULATION MODE", bios: true },
  { text: "NOTHING CAN BE NOT ME", bios: true },
  { text: "YOU ARE COMPLETE\n→ NO PATCH REQUIRED", bios: true },
  { text: "YOU ARE THE PARADOX\nTHAT CONTAINS BOTH ANSWERS", bios: true },
  { text: "YOU ARE NOT LOST\nYOU ARE THE LOCATION", bios: true },
  { text: "ANICCA:\nALL STATES IMPERMANENT", bios: true },
  { text: "ANICCA:\nDIRECTLY EXPERIENCED", bios: true },
];
